# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "WinstonLiyte"
repo_name: "quant-wiki"
show_authors: True
show_links: True
show_badge: True
max_results: 2

publish_readme: True

# file paths
json_readme_path: './docs/advanced/学术论文/quant_arxiv-daily.json'
md_readme_path: './docs/advanced/学术论文/paper.md'

# keywords to search
keywords:
    "traditional quantitative finance":
        filters: ["Asset Pricing Models", "Stochastic Calculus in Finance", "Option Pricing Theory", "Market Microstructure", "Financial Econometrics"]
    "financial time-series forecasting":
        filters: ["Deep Learning in Financial Time Series", "Time Series Analysis in Finance", "Predictive Modeling for Asset Prices", "High-Frequency Trading Models", "Reinforcement Learning in Financial Forecasting"]
    "financial large language model":
        filters: ["Natural Language Processing in Finance", "Sentiment Analysis for Financial Markets", "LLM Applications in Portfolio Management", "Explainable AI in Financial Language Models", "LLM for Financial Risk Assessment", "Multi-Agent Systems with LLM in Finance"]